## Import Libraries

In [208]:
import warnings
warnings.filterwarnings("ignore")

In [210]:
import pandas as pd
import numpy as  np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [211]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

## Data Understanding
### Reading Data

In [213]:
#Reading application.csv 
application_data=pd.read_csv('C:/Users/xyz/Downloads/application_data.csv')
application_data.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,0.0690,0.0833,0.1250,0.0369,0.0202,0.0190,0.0000,0.0000,0.0252,0.0383,0.9722,0.6341,0.0144,0.0000,0.0690,0.0833,0.1250,0.0377,0.022,0.0198,0.0,0.0,0.0250,0.0369,0.9722,0.6243,0.0144,0.00,0.0690,0.0833,0.1250,0.0375,0.0205,0.0193,0.0000,0.00,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.079,0.0554,0.0,0.0,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.010032,-19046,-225,-4260.0,-2531,26.0,1,1,1,1,1,0,Laborers,1.0,2,2,MONDAY,9,0,0,0,0,0,0,Government,NaN,0.555912,0.729567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-815.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.008019,-19005,-3039,-9833.0,-2437,NaN,1,1,0,1,0,0,Laborers,2.0,2,2,WEDNESDAY,17,0,0,0,0,0,0,Business Entity Type 3,NaN,0.650442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,2.0,0.0,-617.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,513000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.028663,-19932,-3038,-4311.0,-3458,NaN,1,1,0,1,0,0,Core staff,1.0,2,2,THURSDAY,11,0,0,0,0,1,1,Religion,NaN,0.322738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-1106.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

### Understanding the data

In [214]:
#Finding rows and column
application_data.shape

(307511, 122)

In [215]:
application_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Columns: 122 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(65), int64(41), object(16)
memory usage: 286.2+ MB

In [216]:
# Finding summary for the numeric column
application_data.describe()

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,TOTALAREA_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
count,307511.000000,307511.000000,307511.000000,3.075110e+05,3.075110e+05,307499.000000,3.072330e+05,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,104582.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307509.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,134133.000000,3.068510e+05,246546.000000,151450.00000,127568.000000,157504.000000,103023.000000,92646.000000,143620.000000,152683.000000,154491.000000,98869.000000,124921.000000,97312.000000,153161.000000,93997.000000,137829.000000,151450.000000,127568.000000,157504.000000,103023.000000,92646.000000,143620.000000,152683.000000,154491.000000,98869.000000,124921.000000,97312.000000,153161.000000,93997.000000,137829.000000,151450.000000,127568.000000,157504.000000,103023.000000,92646.000000,143620.000000,152683.000000,154491.000000,98869.000000,124921.000000,97312.000000,153161.000000,93997.000000,137829.000000,159080.000000,306490.000000,306490.000000,306490.000000,306490.000000,307510.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.00000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,265992.000000,265992.000000,265992.000000,265992.000000,265992.000000,265992.000000
mean,278180.518577,0.080729,0.417052,1.687979e+05,5.990260e+05,27108.573909,5.383962e+05,0.020868,-16036.995067,63815.045904,-4986.120328,-2994.202373,12.061091,0.999997,0.819889,0.199368,0.998133,0.281066,0.056720,2.152665,2.052463,2.031521,12.063419,0.015144,0.050769,0.040659,0.078173,0.230454,0.179555,0.502130,5.143927e-01,0.510853,0.11744,0.088442,0.977735,0.752471,0.044621,0.078942,0.149725,0.226282,0.231894,0.066333,0.100775,0.107399,0.008809,0.028358,0.114231,0.087543,0.977065,0.759637,0.042553,0.074490,0.145193,0.222315,0.228058,0.064958,0.105645,0.105975,0.008076,0.027022,0.117850,0.087955,0.977752,0.755746,0.044595,0.078078,0.149213,0.225897,0.231625,0.067169,0.101954,0.108607,0.008651,0.028236,0.102547,1.422245,0.143421,1.405292,0.100049,-962.858788,0.000042,0.710023,0.000081,0.015115,0.088055,0.000192,0.081376,0.003896,0.000023,0.003912,0.000007,0.003525,0.002936,0.00121,0.009928,0.000267,0.008130,0.000595,0.000507,0.000335,0.006402,0.007000,0.034362,0.267395,0.265474,1.899974
std,102790.175348,0.272419,0.722121,2.371231e+05,4.024908e+05,14493.737315,3.694465e+05,0.013831,4363.988632,141275.766519,3522.886321,1509.450419,11.944812,0.001803,0.384280,0.399526,0.043164,0.449521,0.231307,0.910682,0.509034,0.502737,3.265832,0.122126,0.219526,0.197499,0.268444,0.421124,0.383817,0.211062,1.910602e-01,0.194844,0.10824,0.082438,0.059223,0.113280,0.076036,0.134576,0.100049,0.144641,0.161380,0.081184,0.092576,0.110565,0.047732,0.069523,0.107936,0.084307,0.064575,0.110111,0.074445,0.132256,0.100977,0.143709,0.161160,0.081750,0.097880,0.111845,0.046276,0.070254,0.109076,0.082179,0.059897,0.112066,0.076144,0.134467,0.100368,0.145067,0.161934,0.082167,0.093642,0.112260,0.047415,0.070166,0.107462,2.400989,0.446698,2.379803,0.362291,826.808487,0.006502,0.453752,0.009016,0.122010,0.283376,0.013850,0.273412,0.062295,0.004771,0.062424,0.002550,0.059268,0.054110,0.03476,0.099144,0.016327,0.089798,0.024387,0.022518,0.018299,0.083849,0.110757,0.204685,0.916002,0.794056,1.869295
min,100002.000000,0.000000,0.000000,2.565000e+04,4.500000e+04,1615.500000,4.050000e+04,0.000290,-25229.000000,-17912.000000,-24672.000000,-7197.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.014568,8.173617e-08,0.000527,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-4292.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,189145.500000,0.000000,0.000000,1.125000e+05,2.700000e+05,16524.000000,2.385000e+05,0.010006,-19682.000000,-2760.000000,-7479.500000,-4299.000000,5.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,2.000000,2.000000,2.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.334007,3.924574e-01,0.370650,0.05770,0.044200,0.976700,0.687200,0.007800,0.000000,0.069000,0.166700,0.083300,0.018700,0.050400,0.045300,0.000000,0.000000,0.052500,0.040700,0.976700,0.699400,0.007200,0.000000,0.069000,0.166700,0.083300,0.016600,0.054200,0.042700,0.000000,0.000000,0.058300,0.043700,0.976700,0.691400,0.007900,0.000000,0.069000,0.166700,0.083300,0.018700,0.051300,0.045700,0.000000,0.000000,0.041200,0.000000,0.000000,0.000000,0.000000,-1570.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,278202.000000,0.000000,0.000000,1.471500e+05,5.135310e+05,24903.000000,4.500000e+05,0.018850,-15750.000000,-1213.000000,-4504.000000,-3254.000000,9.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,2.000000,2.000000,2.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.505998,5.659614e-01,0.535276,0.08760,0.076300,0.981600,0.755200,0.021100,0.000000,0.137900,0.166700,0.208300,0.048100,0.075600,0.074500,0.000000,0.003600,0.084000,0.074600,0.981600,0.764800,0.019000,0.000000,0.137900,0.166700,0.208300,0.045800,0.077100,0.073100,0.000000,0.001100,0.086400,0.075800,0.981600,0.758500,0.020800,0.000000,0.137900,0.166700,0.208300,0.048700,0.076100,0.074900,0.000000,0.003100,0.068800,0.000000,0.000000,0.000000,0.000000,-757.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,367142.500000,0.000000,1.000000,2.025000e+05,8.086500e+05,34596.000000,6.795000e+05,0.028663,-12413.000000,-289.000000,-2010.000000,-1720.000000,15.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,3.000000,2.000000,2.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.675053,6.636171e-01,0.669057,0.14850,0.112200,0.986600,0.823200,0.051500,0.120000,0.206900,0.333300,0.375000,0.085600,0.121000,0.129900,0.003900,0.027700,0.143900,0.112400,0.986600,0.823600,0.049000,0.120800,0.206900,0.333300,0.375000,0.084100,0.131300,0.125200,0.003900,0.023100,0.148900,0.111600,0.986600,0.825600,0.051300,0.120000,0.206900,0.333300,0.375000,0.086800,0.123100,0.130300,0.003900,0.026600,0.127600,2.000000,0.000000,2.000000,0.000000,-274.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
max,456255.000000,1.000000,19.000000,1.170000e+08,4.050000e+06,258025.500000,4.050000e+06,0.072508,-7489.000000,365243.000000,0.000000,0.000000,91.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,20.000000,3.000000,3.000000,23.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.962693,8.549997e-01,0.896010,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,348.000000,34.000000,344.000000,24.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,9.000000,8.000000,27.000000,261.000000,25.000000

In [217]:
#find the null values in each column 
application_data.isnull().sum()

SK_ID_CURR                           0
TARGET                               0
NAME_CONTRACT_TYPE                   0
CODE_GENDER                          0
FLAG_OWN_CAR                         0
FLAG_OWN_REALTY                      0
CNT_CHILDREN                         0
AMT_INCOME_TOTAL                     0
AMT_CREDIT                           0
AMT_ANNUITY                         12
AMT_GOODS_PRICE                    278
NAME_TYPE_SUITE                   1292
NAME_INCOME_TYPE                     0
NAME_EDUCATION_TYPE                  0
NAME_FAMILY_STATUS                   0
NAME_HOUSING_TYPE                    0
REGION_POPULATION_RELATIVE           0
DAYS_BIRTH                           0
DAYS_EMPLOYED                        0
DAYS_REGISTRATION                    0
DAYS_ID_PUBLISH                      0
OWN_CAR_AGE                     202929
FLAG_MOBIL                           0
FLAG_EMP_PHONE                       0
FLAG_WORK_PHONE                      0
FLAG_CONT_MOBILE                     0
FLAG_PHONE                           0
FLAG_EMAIL                           0
OCCUPATION_TYPE                  96391
CNT_FAM_MEMBERS                      2
REGION_RATING_CLIENT                 0
REGION_RATING_CLIENT_W_CITY          0
WEEKDAY_APPR_PROCESS_START           0
HOUR_APPR_PROCESS_START              0
REG_REGION_NOT_LIVE_REGION           0
REG_REGION_NOT_WORK_REGION           0
LIVE_REGION_NOT_WORK_REGION          0
REG_CITY_NOT_LIVE_CITY               0
REG_CITY_NOT_WORK_CITY               0
LIVE_CITY_NOT_WORK_CITY              0
ORGANIZATION_TYPE                    0
EXT_SOURCE_1                    173378
EXT_SOURCE_2                       660
EXT_SOURCE_3                     60965
APARTMENTS_AVG                  156061
BASEMENTAREA_AVG                179943
YEARS_BEGINEXPLUATATION_AVG     150007
YEARS_BUILD_AVG                 204488
COMMONAREA_AVG                  214865
ELEVATORS_AVG                   163891
ENTRANCES_AVG                   154828
FLOORSMAX_AVG                   153020
FLOORSMIN_AVG                   208642
LANDAREA_AVG                    182590
LIVINGAPARTMENTS_AVG            210199
LIVINGAREA_AVG                  154350
NONLIVINGAPARTMENTS_AVG         213514
NONLIVINGAREA_AVG               169682
APARTMENTS_MODE                 156061
BASEMENTAREA_MODE               179943
YEARS_BEGINEXPLUATATION_MODE    150007
YEARS_BUILD_MODE                204488
COMMONAREA_MODE                 214865
ELEVATORS_MODE                  163891
ENTRANCES_MODE                  154828
FLOORSMAX_MODE                  153020
FLOORSMIN_MODE                  208642
LANDAREA_MODE                   182590
LIVINGAPARTMENTS_MODE           210199
LIVINGAREA_MODE                 154350
NONLIVINGAPARTMENTS_MODE        213514
NONLIVINGAREA_MODE              169682
APARTMENTS_MEDI                 156061
BASEMENTAREA_MEDI               179943
YEARS_BEGINEXPLUATATION_MEDI    150007
YEARS_BUILD_MEDI                204488
COMMONAREA_MEDI                 214865
ELEVATORS_MEDI                  163891
ENTRANCES_MEDI                  154828
FLOORSMAX_MEDI                  153020
FLOORSMIN_MEDI                  208642
LANDAREA_MEDI                   182590
LIVINGAPARTMENTS_MEDI           210199
LIVINGAREA_MEDI                 154350
NONLIVINGAPARTMENTS_MEDI        213514
NONLIVINGAREA_MEDI              169682
FONDKAPREMONT_MODE              210295
HOUSETYPE_MODE                  154297
TOTALAREA_MODE                  148431
WALLSMATERIAL_MODE              156341
EMERGENCYSTATE_MODE             145755
OBS_30_CNT_SOCIAL_CIRCLE          1021
DEF_30_CNT_SOCIAL_CIRCLE          1021
OBS_60_CNT_SOCIAL_CIRCLE          1021
DEF_60_CNT_SOCIAL_CIRCLE          1021
DAYS_LAST_PHONE_CHANGE               1
FLAG_DOCUMENT_2                      0
FLAG_DOCUMENT_3                      0
FLAG_DOCUMENT_4                      0
FLAG_DOCUMENT_5                      0
FLAG_DOCUMENT_6                      0
FLAG_DOCUMENT_7                      0
FLAG_DOCUMENT_8                      0
FLAG_DOCUMENT_9                      0
FLAG_DOCUMENT_10                     0
FLAG_DOCUMENT_11                     0
FLAG_DOCUMENT_12                     0
FLAG_DOCUMENT_13                     0
FLAG_DOCUMENT_14                     0
FLAG_DOCUMENT_15                     0
FLAG_DOCUMENT_16                     0
FLAG_DOCUMENT_17                     0
FLAG_DOCUMENT_18                     0
FLAG_DOCUMENT_19                     0
FLAG_DOCUMENT_20                     0
FLAG_DOCUMENT_21                     0
AMT_REQ_CREDIT_BUREAU_HOUR       41519
AMT_REQ_CREDIT_BUREAU_DAY        41519
AMT_REQ_CREDIT_BUREAU_WEEK       41519
AMT_REQ_CREDIT_BUREAU_MON        41519
AMT_REQ_CREDIT_BUREAU_QRT        41519
AMT_REQ_CREDIT_BUREAU_YEAR       41519
dtype: int64

In [218]:
#find the percentage of null values in each column
(application_data.isnull().sum()*100/ len(application_data))*round(2)

SK_ID_CURR                        0.000000
TARGET                            0.000000
NAME_CONTRACT_TYPE                0.000000
CODE_GENDER                       0.000000
FLAG_OWN_CAR                      0.000000
FLAG_OWN_REALTY                   0.000000
CNT_CHILDREN                      0.000000
AMT_INCOME_TOTAL                  0.000000
AMT_CREDIT                        0.000000
AMT_ANNUITY                       0.007805
AMT_GOODS_PRICE                   0.180807
NAME_TYPE_SUITE                   0.840295
NAME_INCOME_TYPE                  0.000000
NAME_EDUCATION_TYPE               0.000000
NAME_FAMILY_STATUS                0.000000
NAME_HOUSING_TYPE                 0.000000
REGION_POPULATION_RELATIVE        0.000000
DAYS_BIRTH                        0.000000
DAYS_EMPLOYED                     0.000000
DAYS_REGISTRATION                 0.000000
DAYS_ID_PUBLISH                   0.000000
OWN_CAR_AGE                     131.981620
FLAG_MOBIL                        0.000000
FLAG_EMP_PHONE                    0.000000
FLAG_WORK_PHONE                   0.000000
FLAG_CONT_MOBILE                  0.000000
FLAG_PHONE                        0.000000
FLAG_EMAIL                        0.000000
OCCUPATION_TYPE                  62.691091
CNT_FAM_MEMBERS                   0.001301
REGION_RATING_CLIENT              0.000000
REGION_RATING_CLIENT_W_CITY       0.000000
WEEKDAY_APPR_PROCESS_START        0.000000
HOUR_APPR_PROCESS_START           0.000000
REG_REGION_NOT_LIVE_REGION        0.000000
REG_REGION_NOT_WORK_REGION        0.000000
LIVE_REGION_NOT_WORK_REGION       0.000000
REG_CITY_NOT_LIVE_CITY            0.000000
REG_CITY_NOT_WORK_CITY            0.000000
LIVE_CITY_NOT_WORK_CITY           0.000000
ORGANIZATION_TYPE                 0.000000
EXT_SOURCE_1                    112.762145
EXT_SOURCE_2                      0.429253
EXT_SOURCE_3                     39.650614
APARTMENTS_AVG                  101.499459
BASEMENTAREA_AVG                117.031911
YEARS_BEGINEXPLUATATION_AVG      97.562038
YEARS_BUILD_AVG                 132.995568
COMMONAREA_AVG                  139.744595
ELEVATORS_AVG                   106.591959
ENTRANCES_AVG                   100.697536
FLOORSMAX_AVG                    99.521643
FLOORSMIN_AVG                   135.697260
LANDAREA_AVG                    118.753475
LIVINGAPARTMENTS_AVG            136.709906
LIVINGAREA_AVG                  100.386653
NONLIVINGAPARTMENTS_AVG         138.865927
NONLIVINGAREA_AVG               110.358329
APARTMENTS_MODE                 101.499459
BASEMENTAREA_MODE               117.031911
YEARS_BEGINEXPLUATATION_MODE     97.562038
YEARS_BUILD_MODE                132.995568
COMMONAREA_MODE                 139.744595
ELEVATORS_MODE                  106.591959
ENTRANCES_MODE                  100.697536
FLOORSMAX_MODE                   99.521643
FLOORSMIN_MODE                  135.697260
LANDAREA_MODE                   118.753475
LIVINGAPARTMENTS_MODE           136.709906
LIVINGAREA_MODE                 100.386653
NONLIVINGAPARTMENTS_MODE        138.865927
NONLIVINGAREA_MODE              110.358329
APARTMENTS_MEDI                 101.499459
BASEMENTAREA_MEDI               117.031911
YEARS_BEGINEXPLUATATION_MEDI     97.562038
YEARS_BUILD_MEDI                132.995568
COMMONAREA_MEDI                 139.744595
ELEVATORS_MEDI                  106.591959
ENTRANCES_MEDI                  100.697536
FLOORSMAX_MEDI                   99.521643
FLOORSMIN_MEDI                  135.697260
LANDAREA_MEDI                   118.753475
LIVINGAPARTMENTS_MEDI           136.709906
LIVINGAREA_MEDI                 100.386653
NONLIVINGAPARTMENTS_MEDI        138.865927
NONLIVINGAREA_MEDI              110.358329
FONDKAPREMONT_MODE              136.772343
HOUSETYPE_MODE                  100.352183
TOTALAREA_MODE                   96.537034
WALLSMATERIAL_MODE              101.681566
EMERGENCYSTATE_MODE              94.796609
OBS_30_CNT_SOCIAL_CIRCLE          0.664041
DEF_30_CNT_SOCIAL_CIRCLE          0.664041
OBS_60_CNT_SOCIAL_CIRCLE          0.664041
DEF_60_CNT_SOCIAL_CIRCLE          0.664041
DAYS_LAST_PHONE_CHANGE            0.000650
FLAG_DOCUMENT_2                   0.000000
FLAG_DOCUMENT_3                   0.000000
FLAG_DOCUMENT_4                   0.000000
FLAG_DOCUMENT_5                   0.000000
FLAG_DOCUMENT_6                   0.000000
FLAG_DOCUMENT_7                   0.000000
FLAG_DOCUMENT_8                   0.000000
FLAG_DOCUMENT_9                   0.000000
FLAG_DOCUMENT_10                  0.000000
FLAG_DOCUMENT_11                  0.000000
FLAG_DOCUMENT_12                  0.000000
FLAG_DOCUMENT_13                  0.000000
FLAG_DOCUMENT_14                  0.000000
FLAG_DOCUMENT_15                  0.000000
FLAG_DOCUMENT_16                  0.000000
FLAG_DOCUMENT_17                  0.000000
FLAG_DOCUMENT_18                  0.000000
FLAG_DOCUMENT_19                  0.000000
FLAG_DOCUMENT_20                  0.000000
FLAG_DOCUMENT_21                  0.000000
AMT_REQ_CREDIT_BUREAU_HOUR       27.003262
AMT_REQ_CREDIT_BUREAU_DAY        27.003262
AMT_REQ_CREDIT_BUREAU_WEEK       27.003262
AMT_REQ_CREDIT_BUREAU_MON        27.003262
AMT_REQ_CREDIT_BUREAU_QRT        27.003262
AMT_REQ_CREDIT_BUREAU_YEAR       27.003262
dtype: float64

## Data Cleaning

In [219]:
#list of columns
list(application_data.columns)

['SK_ID_CURR',
 'TARGET',
 'NAME_CONTRACT_TYPE',
 'CODE_GENDER',
 'FLAG_OWN_CAR',
 'FLAG_OWN_REALTY',
 'CNT_CHILDREN',
 'AMT_INCOME_TOTAL',
 'AMT_CREDIT',
 'AMT_ANNUITY',
 'AMT_GOODS_PRICE',
 'NAME_TYPE_SUITE',
 'NAME_INCOME_TYPE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'REGION_POPULATION_RELATIVE',
 'DAYS_BIRTH',
 'DAYS_EMPLOYED',
 'DAYS_REGISTRATION',
 'DAYS_ID_PUBLISH',
 'OWN_CAR_AGE',
 'FLAG_MOBIL',
 'FLAG_EMP_PHONE',
 'FLAG_WORK_PHONE',
 'FLAG_CONT_MOBILE',
 'FLAG_PHONE',
 'FLAG_EMAIL',
 'OCCUPATION_TYPE',
 'CNT_FAM_MEMBERS',
 'REGION_RATING_CLIENT',
 'REGION_RATING_CLIENT_W_CITY',
 'WEEKDAY_APPR_PROCESS_START',
 'HOUR_APPR_PROCESS_START',
 'REG_REGION_NOT_LIVE_REGION',
 'REG_REGION_NOT_WORK_REGION',
 'LIVE_REGION_NOT_WORK_REGION',
 'REG_CITY_NOT_LIVE_CITY',
 'REG_CITY_NOT_WORK_CITY',
 'LIVE_CITY_NOT_WORK_CITY',
 'ORGANIZATION_TYPE',
 'EXT_SOURCE_1',
 'EXT_SOURCE_2',
 'EXT_SOURCE_3',
 'APARTMENTS_AVG',
 'BASEMENTAREA_AVG',
 'YEARS_BEGINEXPLUATATION_AVG',
 'YEARS_BUILD_AVG',
 'COMMONAREA_AVG',
 'ELEVATORS_AVG',
 'ENTRANCES_AVG',
 'FLOORSMAX_AVG',
 'FLOORSMIN_AVG',
 'LANDAREA_AVG',
 'LIVINGAPARTMENTS_AVG',
 'LIVINGAREA_AVG',
 'NONLIVINGAPARTMENTS_AVG',
 'NONLIVINGAREA_AVG',
 'APARTMENTS_MODE',
 'BASEMENTAREA_MODE',
 'YEARS_BEGINEXPLUATATION_MODE',
 'YEARS_BUILD_MODE',
 'COMMONAREA_MODE',
 'ELEVATORS_MODE',
 'ENTRANCES_MODE',
 'FLOORSMAX_MODE',
 'FLOORSMIN_MODE',
 'LANDAREA_MODE',
 'LIVINGAPARTMENTS_MODE',
 'LIVINGAREA_MODE',
 'NONLIVINGAPARTMENTS_MODE',
 'NONLIVINGAREA_MODE',
 'APARTMENTS_MEDI',
 'BASEMENTAREA_MEDI',
 'YEARS_BEGINEXPLUATATION_MEDI',
 'YEARS_BUILD_MEDI',
 'COMMONAREA_MEDI',
 'ELEVATORS_MEDI',
 'ENTRANCES_MEDI',
 'FLOORSMAX_MEDI',
 'FLOORSMIN_MEDI',
 'LANDAREA_MEDI',
 'LIVINGAPARTMENTS_MEDI',
 'LIVINGAREA_MEDI',
 'NONLIVINGAPARTMENTS_MEDI',
 'NONLIVINGAREA_MEDI',
 'FONDKAPREMONT_MODE',
 'HOUSETYPE_MODE',
 'TOTALAREA_MODE',
 'WALLSMATERIAL_MODE',
 'EMERGENCYSTATE_MODE',
 'OBS_30_CNT_SOCIAL_CIRCLE',
 'DEF_30_CNT_SOCIAL_CIRCLE',
 'OBS_60_CNT_SOCIAL_CIRCLE',
 'DEF_60_CNT_SOCIAL_CIRCLE',
 'DAYS_LAST_PHONE_CHANGE',
 'FLAG_DOCUMENT_2',
 'FLAG_DOCUMENT_3',
 'FLAG_DOCUMENT_4',
 'FLAG_DOCUMENT_5',
 'FLAG_DOCUMENT_6',
 'FLAG_DOCUMENT_7',
 'FLAG_DOCUMENT_8',
 'FLAG_DOCUMENT_9',
 'FLAG_DOCUMENT_10',
 'FLAG_DOCUMENT_11',
 'FLAG_DOCUMENT_12',
 'FLAG_DOCUMENT_13',
 'FLAG_DOCUMENT_14',
 'FLAG_DOCUMENT_15',
 'FLAG_DOCUMENT_16',
 'FLAG_DOCUMENT_17',
 'FLAG_DOCUMENT_18',
 'FLAG_DOCUMENT_19',
 'FLAG_DOCUMENT_20',
 'FLAG_DOCUMENT_21',
 'AMT_REQ_CREDIT_BUREAU_HOUR',
 'AMT_REQ_CREDIT_BUREAU_DAY',
 'AMT_REQ_CREDIT_BUREAU_WEEK',
 'AMT_REQ_CREDIT_BUREAU_MON',
 'AMT_REQ_CREDIT_BUREAU_QRT',
 'AMT_REQ_CREDIT_BUREAU_YEAR']

In [220]:
#Calculate the percentage of NaN 
def get_perc_of_missing_values(series):
    num=series.isnull().sum()
    den=len(series)
    return round(num/den, 3)
get_perc_of_missing_values(application_data)

SK_ID_CURR                      0.000
TARGET                          0.000
NAME_CONTRACT_TYPE              0.000
CODE_GENDER                     0.000
FLAG_OWN_CAR                    0.000
FLAG_OWN_REALTY                 0.000
CNT_CHILDREN                    0.000
AMT_INCOME_TOTAL                0.000
AMT_CREDIT                      0.000
AMT_ANNUITY                     0.000
AMT_GOODS_PRICE                 0.001
NAME_TYPE_SUITE                 0.004
NAME_INCOME_TYPE                0.000
NAME_EDUCATION_TYPE             0.000
NAME_FAMILY_STATUS              0.000
NAME_HOUSING_TYPE               0.000
REGION_POPULATION_RELATIVE      0.000
DAYS_BIRTH                      0.000
DAYS_EMPLOYED                   0.000
DAYS_REGISTRATION               0.000
DAYS_ID_PUBLISH                 0.000
OWN_CAR_AGE                     0.660
FLAG_MOBIL                      0.000
FLAG_EMP_PHONE                  0.000
FLAG_WORK_PHONE                 0.000
FLAG_CONT_MOBILE                0.000
FLAG_PHONE                      0.000
FLAG_EMAIL                      0.000
OCCUPATION_TYPE                 0.313
CNT_FAM_MEMBERS                 0.000
REGION_RATING_CLIENT            0.000
REGION_RATING_CLIENT_W_CITY     0.000
WEEKDAY_APPR_PROCESS_START      0.000
HOUR_APPR_PROCESS_START         0.000
REG_REGION_NOT_LIVE_REGION      0.000
REG_REGION_NOT_WORK_REGION      0.000
LIVE_REGION_NOT_WORK_REGION     0.000
REG_CITY_NOT_LIVE_CITY          0.000
REG_CITY_NOT_WORK_CITY          0.000
LIVE_CITY_NOT_WORK_CITY         0.000
ORGANIZATION_TYPE               0.000
EXT_SOURCE_1                    0.564
EXT_SOURCE_2                    0.002
EXT_SOURCE_3                    0.198
APARTMENTS_AVG                  0.507
BASEMENTAREA_AVG                0.585
YEARS_BEGINEXPLUATATION_AVG     0.488
YEARS_BUILD_AVG                 0.665
COMMONAREA_AVG                  0.699
ELEVATORS_AVG                   0.533
ENTRANCES_AVG                   0.503
FLOORSMAX_AVG                   0.498
FLOORSMIN_AVG                   0.678
LANDAREA_AVG                    0.594
LIVINGAPARTMENTS_AVG            0.684
LIVINGAREA_AVG                  0.502
NONLIVINGAPARTMENTS_AVG         0.694
NONLIVINGAREA_AVG               0.552
APARTMENTS_MODE                 0.507
BASEMENTAREA_MODE               0.585
YEARS_BEGINEXPLUATATION_MODE    0.488
YEARS_BUILD_MODE                0.665
COMMONAREA_MODE                 0.699
ELEVATORS_MODE                  0.533
ENTRANCES_MODE                  0.503
FLOORSMAX_MODE                  0.498
FLOORSMIN_MODE                  0.678
LANDAREA_MODE                   0.594
LIVINGAPARTMENTS_MODE           0.684
LIVINGAREA_MODE                 0.502
NONLIVINGAPARTMENTS_MODE        0.694
NONLIVINGAREA_MODE              0.552
APARTMENTS_MEDI                 0.507
BASEMENTAREA_MEDI               0.585
YEARS_BEGINEXPLUATATION_MEDI    0.488
YEARS_BUILD_MEDI                0.665
COMMONAREA_MEDI                 0.699
ELEVATORS_MEDI                  0.533
ENTRANCES_MEDI                  0.503
FLOORSMAX_MEDI                  0.498
FLOORSMIN_MEDI                  0.678
LANDAREA_MEDI                   0.594
LIVINGAPARTMENTS_MEDI           0.684
LIVINGAREA_MEDI                 0.502
NONLIVINGAPARTMENTS_MEDI        0.694
NONLIVINGAREA_MEDI              0.552
FONDKAPREMONT_MODE              0.684
HOUSETYPE_MODE                  0.502
TOTALAREA_MODE                  0.483
WALLSMATERIAL_MODE              0.508
EMERGENCYSTATE_MODE             0.474
OBS_30_CNT_SOCIAL_CIRCLE        0.003
DEF_30_CNT_SOCIAL_CIRCLE        0.003
OBS_60_CNT_SOCIAL_CIRCLE        0.003
DEF_60_CNT_SOCIAL_CIRCLE        0.003
DAYS_LAST_PHONE_CHANGE          0.000
FLAG_DOCUMENT_2                 0.000
FLAG_DOCUMENT_3                 0.000
FLAG_DOCUMENT_4                 0.000
FLAG_DOCUMENT_5                 0.000
FLAG_DOCUMENT_6                 0.000
FLAG_DOCUMENT_7                 0.000
FLAG_DOCUMENT_8                 0.000
FLAG_DOCUMENT_9                 0.000
FLAG_DOCUMENT_10                0.000
FLAG_DOCUMENT_11                0.000
FLAG_DOCUMENT_12                0.000
FLAG_DOCUMENT_13                0.000
FLAG_DOCUMENT_14                0.000
FLAG_DOCUMENT_15                0.000
FLAG_DOCUMENT_16                0.000
FLAG_DOCUMENT_17                0.000
FLAG_DOCUMENT_18                0.000
FLAG_DOCUMENT_19                0.000
FLAG_DOCUMENT_20                0.000
FLAG_DOCUMENT_21                0.000
AMT_REQ_CREDIT_BUREAU_HOUR      0.135
AMT_REQ_CREDIT_BUREAU_DAY       0.135
AMT_REQ_CREDIT_BUREAU_WEEK      0.135
AMT_REQ_CREDIT_BUREAU_MON       0.135
AMT_REQ_CREDIT_BUREAU_QRT       0.135
AMT_REQ_CREDIT_BUREAU_YEAR      0.135
dtype: float64

In [222]:
# iterate over column in application data and delete columns in which 30% of data are null
for col, values in  application_data.iteritems():
    if get_perc_of_missing_values(application_data[col])> 0.30:
        application_data.drop(col, axis=1, inplace=True)
application_data

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_2,EXT_SOURCE_3,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,1,1,0,1,1,0,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.262949,0.139376,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,1,1,0,1,1,0,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.622246,NaN,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.010032,-19046,-225,-4260.0,-2531,1,1,1,1,1,0,1.0,2,2,MONDAY,9,0,0,0,0,0,0,Government,0.555912,0.729567,0.0,0.0,0.0,0.0,-815.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.008019,-19005,-3039,-9833.0,-2437,1,1,0,1,0,0,2.0,2,2,WEDNESDAY,17,0,0,0,0,0,0,Business Entity Type 3,0.650442,NaN,2.0,0.0,2.0,0.0,-617.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,513000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.028663,-19932,-3038,-4311.0,-3458,1,1,0,1,0,0,1.0,2,2,THURSDAY,11,0,0,0,0,1,1,Religion,0.322738,NaN,0.0,0.0,0.0,0.0,-1106.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,225000.0,Unaccompanied,Working,Secondary / secondary special,Separated,With parents,0.032561,-9327,-236,-8456.0,-1982,1,1,0,1,0,0,1.0,1,1,THURSDAY,15,0,0,0,0,0,0,Services,0.681632,NaN,0.0,0.0,0.0,0.0,-273.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307507,456252,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,225000.0,Unaccompanied,Pensioner,Secondary / secondary special,Widow,House / apartment,0.025164,-20775,365243,-4388.0,-4090,1,0,0,1,1,0,1.0,2,2,MONDAY,8,0,0,0,0,0,0,XNA,0.115992,NaN,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307508,456253,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,585000.0,Unaccompanied,Working,Higher education,Separated,House / apartment,0.005002,-14966,-7921,-6737.0,-5150,1,1,0,1,0,1,1.0,3,3,THURSDAY,9,0,0,0,0,1,1,School,0.535722,0.218859,6.0,0.0,6.0,0.0,-1909.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0
307509,456254,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,319500.0,Unaccompanied,Commercial associate,Secondary / secondary special,Married,House / apartment,0.005313,-11961,-4786,-2562.0,-931,1,1,0,1,0,0,2.0,2,2,WEDNESDAY,9,0,0,0,1,1,0,Business Entity Type 1,0.514163,0.661024,0.0,0.0,0.0,0.0,-322.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307510,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,675000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.046220,-16856,-1262,-5128.0,-410,1,1,1,1,1,0,2.0,1,1,THURSDAY,20,0,0,0,0,1,1,Business Entity Type 3,0.708569,0.113922,0.0,0.0,0.0,0.0,-787.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0

In [223]:
application_data.shape

(307511, 72)

In [224]:
#find the percentage of null values in each column
(application_data.isnull().sum() *100/len(application_data)).round(2)

SK_ID_CURR                      0.00
TARGET                          0.00
NAME_CONTRACT_TYPE              0.00
CODE_GENDER                     0.00
FLAG_OWN_CAR                    0.00
FLAG_OWN_REALTY                 0.00
CNT_CHILDREN                    0.00
AMT_INCOME_TOTAL                0.00
AMT_CREDIT                      0.00
AMT_ANNUITY                     0.00
AMT_GOODS_PRICE                 0.09
NAME_TYPE_SUITE                 0.42
NAME_INCOME_TYPE                0.00
NAME_EDUCATION_TYPE             0.00
NAME_FAMILY_STATUS              0.00
NAME_HOUSING_TYPE               0.00
REGION_POPULATION_RELATIVE      0.00
DAYS_BIRTH                      0.00
DAYS_EMPLOYED                   0.00
DAYS_REGISTRATION               0.00
DAYS_ID_PUBLISH                 0.00
FLAG_MOBIL                      0.00
FLAG_EMP_PHONE                  0.00
FLAG_WORK_PHONE                 0.00
FLAG_CONT_MOBILE                0.00
FLAG_PHONE                      0.00
FLAG_EMAIL                      0.00
CNT_FAM_MEMBERS                 0.00
REGION_RATING_CLIENT            0.00
REGION_RATING_CLIENT_W_CITY     0.00
WEEKDAY_APPR_PROCESS_START      0.00
HOUR_APPR_PROCESS_START         0.00
REG_REGION_NOT_LIVE_REGION      0.00
REG_REGION_NOT_WORK_REGION      0.00
LIVE_REGION_NOT_WORK_REGION     0.00
REG_CITY_NOT_LIVE_CITY          0.00
REG_CITY_NOT_WORK_CITY          0.00
LIVE_CITY_NOT_WORK_CITY         0.00
ORGANIZATION_TYPE               0.00
EXT_SOURCE_2                    0.21
EXT_SOURCE_3                   19.83
OBS_30_CNT_SOCIAL_CIRCLE        0.33
DEF_30_CNT_SOCIAL_CIRCLE        0.33
OBS_60_CNT_SOCIAL_CIRCLE        0.33
DEF_60_CNT_SOCIAL_CIRCLE        0.33
DAYS_LAST_PHONE_CHANGE          0.00
FLAG_DOCUMENT_2                 0.00
FLAG_DOCUMENT_3                 0.00
FLAG_DOCUMENT_4                 0.00
FLAG_DOCUMENT_5                 0.00
FLAG_DOCUMENT_6                 0.00
FLAG_DOCUMENT_7                 0.00
FLAG_DOCUMENT_8                 0.00
FLAG_DOCUMENT_9                 0.00
FLAG_DOCUMENT_10                0.00
FLAG_DOCUMENT_11                0.00
FLAG_DOCUMENT_12                0.00
FLAG_DOCUMENT_13                0.00
FLAG_DOCUMENT_14                0.00
FLAG_DOCUMENT_15                0.00
FLAG_DOCUMENT_16                0.00
FLAG_DOCUMENT_17                0.00
FLAG_DOCUMENT_18                0.00
FLAG_DOCUMENT_19                0.00
FLAG_DOCUMENT_20                0.00
FLAG_DOCUMENT_21                0.00
AMT_REQ_CREDIT_BUREAU_HOUR     13.50
AMT_REQ_CREDIT_BUREAU_DAY      13.50
AMT_REQ_CREDIT_BUREAU_WEEK     13.50
AMT_REQ_CREDIT_BUREAU_MON      13.50
AMT_REQ_CREDIT_BUREAU_QRT      13.50
AMT_REQ_CREDIT_BUREAU_YEAR     13.50
dtype: float64

In [225]:
#Removing Exit_source_3 column since it has almost 20% null values
application_data.drop("EXT_SOURCE_3",axis=1,inplace=True)

In [226]:
application_data.describe()

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,EXT_SOURCE_2,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
count,307511.000000,307511.000000,307511.000000,3.075110e+05,3.075110e+05,307499.000000,3.072330e+05,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307509.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,3.068510e+05,306490.000000,306490.000000,306490.000000,306490.000000,307510.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.00000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,265992.000000,265992.000000,265992.000000,265992.000000,265992.000000,265992.000000
mean,278180.518577,0.080729,0.417052,1.687979e+05,5.990260e+05,27108.573909,5.383962e+05,0.020868,-16036.995067,63815.045904,-4986.120328,-2994.202373,0.999997,0.819889,0.199368,0.998133,0.281066,0.056720,2.152665,2.052463,2.031521,12.063419,0.015144,0.050769,0.040659,0.078173,0.230454,0.179555,5.143927e-01,1.422245,0.143421,1.405292,0.100049,-962.858788,0.000042,0.710023,0.000081,0.015115,0.088055,0.000192,0.081376,0.003896,0.000023,0.003912,0.000007,0.003525,0.002936,0.00121,0.009928,0.000267,0.008130,0.000595,0.000507,0.000335,0.006402,0.007000,0.034362,0.267395,0.265474,1.899974
std,102790.175348,0.272419,0.722121,2.371231e+05,4.024908e+05,14493.737315,3.694465e+05,0.013831,4363.988632,141275.766519,3522.886321,1509.450419,0.001803,0.384280,0.399526,0.043164,0.449521,0.231307,0.910682,0.509034,0.502737,3.265832,0.122126,0.219526,0.197499,0.268444,0.421124,0.383817,1.910602e-01,2.400989,0.446698,2.379803,0.362291,826.808487,0.006502,0.453752,0.009016,0.122010,0.283376,0.013850,0.273412,0.062295,0.004771,0.062424,0.002550,0.059268,0.054110,0.03476,0.099144,0.016327,0.089798,0.024387,0.022518,0.018299,0.083849,0.110757,0.204685,0.916002,0.794056,1.869295
min,100002.000000,0.000000,0.000000,2.565000e+04,4.500000e+04,1615.500000,4.050000e+04,0.000290,-25229.000000,-17912.000000,-24672.000000,-7197.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.173617e-08,0.000000,0.000000,0.000000,0.000000,-4292.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,189145.500000,0.000000,0.000000,1.125000e+05,2.700000e+05,16524.000000,2.385000e+05,0.010006,-19682.000000,-2760.000000,-7479.500000,-4299.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,2.000000,2.000000,2.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.924574e-01,0.000000,0.000000,0.000000,0.000000,-1570.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,278202.000000,0.000000,0.000000,1.471500e+05,5.135310e+05,24903.000000,4.500000e+05,0.018850,-15750.000000,-1213.000000,-4504.000000,-3254.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,2.000000,2.000000,2.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.659614e-01,0.000000,0.000000,0.000000,0.000000,-757.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,367142.500000,0.000000,1.000000,2.025000e+05,8.086500e+05,34596.000000,6.795000e+05,0.028663,-12413.000000,-289.000000,-2010.000000,-1720.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,3.000000,2.000000,2.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.636171e-01,2.000000,0.000000,2.000000,0.000000,-274.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
max,456255.000000,1.000000,19.000000,1.170000e+08,4.050000e+06,258025.500000,4.050000e+06,0.072508,-7489.000000,365243.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,20.000000,3.000000,3.000000,23.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,8.549997e-01,348.000000,34.000000,344.000000,24.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,9.000000,8.000000,27.000000,261.000000,25.000000

In [227]:
for col,values in application_data.iteritems():
    if get_perc_of_missing_values(application_data[col])<0.01:
     print(col,get_perc_of_missing_values(application_data[col]))

SK_ID_CURR 0.0
TARGET 0.0
NAME_CONTRACT_TYPE 0.0
CODE_GENDER 0.0
FLAG_OWN_CAR 0.0
FLAG_OWN_REALTY 0.0
CNT_CHILDREN 0.0
AMT_INCOME_TOTAL 0.0
AMT_CREDIT 0.0
AMT_ANNUITY 0.0
AMT_GOODS_PRICE 0.001
NAME_TYPE_SUITE 0.004
NAME_INCOME_TYPE 0.0
NAME_EDUCATION_TYPE 0.0
NAME_FAMILY_STATUS 0.0
NAME_HOUSING_TYPE 0.0
REGION_POPULATION_RELATIVE 0.0
DAYS_BIRTH 0.0
DAYS_EMPLOYED 0.0
DAYS_REGISTRATION 0.0
DAYS_ID_PUBLISH 0.0
FLAG_MOBIL 0.0
FLAG_EMP_PHONE 0.0
FLAG_WORK_PHONE 0.0
FLAG_CONT_MOBILE 0.0
FLAG_PHONE 0.0
FLAG_EMAIL 0.0
CNT_FAM_MEMBERS 0.0
REGION_RATING_CLIENT 0.0
REGION_RATING_CLIENT_W_CITY 0.0
WEEKDAY_APPR_PROCESS_START 0.0
HOUR_APPR_PROCESS_START 0.0
REG_REGION_NOT_LIVE_REGION 0.0
REG_REGION_NOT_WORK_REGION 0.0
LIVE_REGION_NOT_WORK_REGION 0.0
REG_CITY_NOT_LIVE_CITY 0.0
REG_CITY_NOT_WORK_CITY 0.0
LIVE_CITY_NOT_WORK_CITY 0.0
ORGANIZATION_TYPE 0.0
EXT_SOURCE_2 0.002
OBS_30_CNT_SOCIAL_CIRCLE 0.003
DEF_30_CNT_SOCIAL_CIRCLE 0.003
OBS_60_CNT_SOCIAL_CIRCLE 0.003
DEF_60_CNT_SOCIAL_CIRCLE 0.003
DAYS_LAST_PHONE_CHANGE 0.0
FLAG_DOCUMENT_2 0.0
FLAG_DOCUMENT_3 0.0
FLAG_DOCUMENT_4 0.0
FLAG_DOCUMENT_5 0.0
FLAG_DOCUMENT_6 0.0
FLAG_DOCUMENT_7 0.0
FLAG_DOCUMENT_8 0.0
FLAG_DOCUMENT_9 0.0
FLAG_DOCUMENT_10 0.0
FLAG_DOCUMENT_11 0.0
FLAG_DOCUMENT_12 0.0
FLAG_DOCUMENT_13 0.0
FLAG_DOCUMENT_14 0.0
FLAG_DOCUMENT_15 0.0
FLAG_DOCUMENT_16 0.0
FLAG_DOCUMENT_17 0.0
FLAG_DOCUMENT_18 0.0
FLAG_DOCUMENT_19 0.0
FLAG_DOCUMENT_20 0.0
FLAG_DOCUMENT_21 0.0

In [228]:
#since AMT_GOODS_PRICE,EXT_SOURCE_2, has really low missing value we can fill it with mean value

application_data['AMT_GOODS_PRICE'].fillna((application_data['AMT_GOODS_PRICE'].mean()), inplace=True)
application_data['EXT_SOURCE_2'].fillna((application_data['EXT_SOURCE_2'].mean()), inplace=True)
application_data[["AMT_GOODS_PRICE","EXT_SOURCE_2"]].describe().T

                    count           mean            std           min            25%            50%            75%          max
AMT_GOODS_PRICE  307511.0  538396.207429  369279.426396  4.050000e+04  238500.000000  450000.000000  679500.000000  4050000.000
EXT_SOURCE_2     307511.0       0.514393       0.190855  8.173617e-08       0.392974       0.565467       0.663422        0.855

In [229]:
application_data.NAME_TYPE_SUITE.value_counts()

Unaccompanied      248526
Family              40149
Spouse, partner     11370
Children             3267
Other_B              1770
Other_A               866
Group of people       271
Name: NAME_TYPE_SUITE, dtype: int64

In [230]:
#Unaccompanied data has the highest mode so we can fill missing values with unaccompanied
application_data["NAME_TYPE_SUITE"].fillna(application_data["NAME_TYPE_SUITE"].mode()[0],inplace=True)

## Data Analysis

In [231]:
application_data.describe().T

                                count           mean            std           min            25%            50%            75%           max
SK_ID_CURR                   307511.0  278180.518577  102790.175348  1.000020e+05  189145.500000  278202.000000  367142.500000  4.562550e+05
TARGET                       307511.0       0.080729       0.272419  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
CNT_CHILDREN                 307511.0       0.417052       0.722121  0.000000e+00       0.000000       0.000000       1.000000  1.900000e+01
AMT_INCOME_TOTAL             307511.0  168797.919297  237123.146279  2.565000e+04  112500.000000  147150.000000  202500.000000  1.170000e+08
AMT_CREDIT                   307511.0  599025.999706  402490.776996  4.500000e+04  270000.000000  513531.000000  808650.000000  4.050000e+06
AMT_ANNUITY                  307499.0   27108.573909   14493.737315  1.615500e+03   16524.000000   24903.000000   34596.000000  2.580255e+05
AMT_GOODS_PRICE              307511.0  538396.207429  369279.426396  4.050000e+04  238500.000000  450000.000000  679500.000000  4.050000e+06
REGION_POPULATION_RELATIVE   307511.0       0.020868       0.013831  2.900000e-04       0.010006       0.018850       0.028663  7.250800e-02
DAYS_BIRTH                   307511.0  -16036.995067    4363.988632 -2.522900e+04  -19682.000000  -15750.000000  -12413.000000 -7.489000e+03
DAYS_EMPLOYED                307511.0   63815.045904  141275.766519 -1.791200e+04   -2760.000000   -1213.000000    -289.000000  3.652430e+05
DAYS_REGISTRATION            307511.0   -4986.120328    3522.886321 -2.467200e+04   -7479.500000   -4504.000000   -2010.000000  0.000000e+00
DAYS_ID_PUBLISH              307511.0   -2994.202373    1509.450419 -7.197000e+03   -4299.000000   -3254.000000   -1720.000000  0.000000e+00
FLAG_MOBIL                   307511.0       0.999997       0.001803  0.000000e+00       1.000000       1.000000       1.000000  1.000000e+00
FLAG_EMP_PHONE               307511.0       0.819889       0.384280  0.000000e+00       1.000000       1.000000       1.000000  1.000000e+00
FLAG_WORK_PHONE              307511.0       0.199368       0.399526  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_CONT_MOBILE             307511.0       0.998133       0.043164  0.000000e+00       1.000000       1.000000       1.000000  1.000000e+00
FLAG_PHONE                   307511.0       0.281066       0.449521  0.000000e+00       0.000000       0.000000       1.000000  1.000000e+00
FLAG_EMAIL                   307511.0       0.056720       0.231307  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
CNT_FAM_MEMBERS              307509.0       2.152665       0.910682  1.000000e+00       2.000000       2.000000       3.000000  2.000000e+01
REGION_RATING_CLIENT         307511.0       2.052463       0.509034  1.000000e+00       2.000000       2.000000       2.000000  3.000000e+00
REGION_RATING_CLIENT_W_CITY  307511.0       2.031521       0.502737  1.000000e+00       2.000000       2.000000       2.000000  3.000000e+00
HOUR_APPR_PROCESS_START      307511.0      12.063419       3.265832  0.000000e+00      10.000000      12.000000      14.000000  2.300000e+01
REG_REGION_NOT_LIVE_REGION   307511.0       0.015144       0.122126  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
REG_REGION_NOT_WORK_REGION   307511.0       0.050769       0.219526  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
LIVE_REGION_NOT_WORK_REGION  307511.0       0.040659       0.197499  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
REG_CITY_NOT_LIVE_CITY       307511.0       0.078173       0.268444  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
REG_CITY_NOT_WORK_CITY       307511.0       0.230454       0.421124  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
LIVE_CITY_NOT_WORK_CITY      307511.0       0.179555       0.383817  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
EXT_SOURCE_2                 307511.0       0.514393       0.190855  8.173617e-08       0.392974       0.565467       0.663422  8.549997e-01
OBS_30_CNT_SOCIAL_CIRCLE     306490.0       1.422245       2.400989  0.000000e+00       0.000000       0.000000       2.000000  3.480000e+02
DEF_30_CNT_SOCIAL_CIRCLE     306490.0       0.143421       0.446698  0.000000e+00       0.000000       0.000000       0.000000  3.400000e+01
OBS_60_CNT_SOCIAL_CIRCLE     306490.0       1.405292       2.379803  0.000000e+00       0.000000       0.000000       2.000000  3.440000e+02
DEF_60_CNT_SOCIAL_CIRCLE     306490.0       0.100049       0.362291  0.000000e+00       0.000000       0.000000       0.000000  2.400000e+01
DAYS_LAST_PHONE_CHANGE       307510.0    -962.858788     826.808487 -4.292000e+03   -1570.000000    -757.000000    -274.000000  0.000000e+00
FLAG_DOCUMENT_2              307511.0       0.000042       0.006502  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_3              307511.0       0.710023       0.453752  0.000000e+00       0.000000       1.000000       1.000000  1.000000e+00
FLAG_DOCUMENT_4              307511.0       0.000081       0.009016  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_5              307511.0       0.015115       0.122010  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_6              307511.0       0.088055       0.283376  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_7              307511.0       0.000192       0.013850  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_8              307511.0       0.081376       0.273412  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_9              307511.0       0.003896       0.062295  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_10             307511.0       0.000023       0.004771  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_11             307511.0       0.003912       0.062424  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_12             307511.0       0.000007       0.002550  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_13             307511.0       0.003525       0.059268  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_14             307511.0       0.002936       0.054110  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_15             307511.0       0.001210       0.034760  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_16             307511.0       0.009928       0.099144  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_17             307511.0       0.000267       0.016327  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_18             307511.0       0.008130       0.089798  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_19             307511.0       0.000595       0.024387  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_20             307511.0       0.000507       0.022518  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_21             307511.0       0.000335       0.018299  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
AMT_REQ_CREDIT_BUREAU_HOUR   265992.0       0.006402       0.083849  0.000000e+00       0.000000       0.000000       0.000000  4.000000e+00
AMT_REQ_CREDIT_BUREAU_DAY    265992.0       0.007000       0.110757  0.000000e+00       0.000000       0.000000       0.000000  9.000000e+00
AMT_REQ_CREDIT_BUREAU_WEEK   265992.0       0.034362       0.204685  0.000000e+00       0.000000       0.000000       0.000000  8.000000e+00
AMT_REQ_CREDIT_BUREAU_MON    265992.0       0.267395       0.916002  0.000000e+00       0.000000       0.000000       0.000000  2.700000e+01
AMT_REQ_CREDIT_BUREAU_QRT    265992.0       0.265474       0.794056  0.000000e+00       0.000000       0.000000       0.000000  2.610000e+02
AMT_REQ_CREDIT_BUREAU_YEAR   265992.0       1.899974       1.869295  0.000000e+00       0.000000       1.000000       3.000000  2.500000e+01

In [232]:
#AMT_ANNUITY,CNT_FAM_MEMBERS columns have less miising value so we can fill it with mean value
application_data['AMT_ANNUITY'].fillna((application_data['AMT_ANNUITY'].mean()), inplace=True)
application_data['CNT_FAM_MEMBERS'].fillna((application_data['CNT_FAM_MEMBERS'].mean()), inplace=True)
application_data['DAYS_LAST_PHONE_CHANGE'].fillna((application_data['DAYS_LAST_PHONE_CHANGE'].mean()), inplace=True)

In [233]:
application_data.describe().T

                                count           mean            std           min            25%            50%            75%           max
SK_ID_CURR                   307511.0  278180.518577  102790.175348  1.000020e+05  189145.500000  278202.000000  367142.500000  4.562550e+05
TARGET                       307511.0       0.080729       0.272419  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
CNT_CHILDREN                 307511.0       0.417052       0.722121  0.000000e+00       0.000000       0.000000       1.000000  1.900000e+01
AMT_INCOME_TOTAL             307511.0  168797.919297  237123.146279  2.565000e+04  112500.000000  147150.000000  202500.000000  1.170000e+08
AMT_CREDIT                   307511.0  599025.999706  402490.776996  4.500000e+04  270000.000000  513531.000000  808650.000000  4.050000e+06
AMT_ANNUITY                  307511.0   27108.573909   14493.454517  1.615500e+03   16524.000000   24903.000000   34596.000000  2.580255e+05
AMT_GOODS_PRICE              307511.0  538396.207429  369279.426396  4.050000e+04  238500.000000  450000.000000  679500.000000  4.050000e+06
REGION_POPULATION_RELATIVE   307511.0       0.020868       0.013831  2.900000e-04       0.010006       0.018850       0.028663  7.250800e-02
DAYS_BIRTH                   307511.0  -16036.995067    4363.988632 -2.522900e+04  -19682.000000  -15750.000000  -12413.000000 -7.489000e+03
DAYS_EMPLOYED                307511.0   63815.045904  141275.766519 -1.791200e+04   -2760.000000   -1213.000000    -289.000000  3.652430e+05
DAYS_REGISTRATION            307511.0   -4986.120328    3522.886321 -2.467200e+04   -7479.500000   -4504.000000   -2010.000000  0.000000e+00
DAYS_ID_PUBLISH              307511.0   -2994.202373    1509.450419 -7.197000e+03   -4299.000000   -3254.000000   -1720.000000  0.000000e+00
FLAG_MOBIL                   307511.0       0.999997       0.001803  0.000000e+00       1.000000       1.000000       1.000000  1.000000e+00
FLAG_EMP_PHONE               307511.0       0.819889       0.384280  0.000000e+00       1.000000       1.000000       1.000000  1.000000e+00
FLAG_WORK_PHONE              307511.0       0.199368       0.399526  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_CONT_MOBILE             307511.0       0.998133       0.043164  0.000000e+00       1.000000       1.000000       1.000000  1.000000e+00
FLAG_PHONE                   307511.0       0.281066       0.449521  0.000000e+00       0.000000       0.000000       1.000000  1.000000e+00
FLAG_EMAIL                   307511.0       0.056720       0.231307  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
CNT_FAM_MEMBERS              307511.0       2.152665       0.910679  1.000000e+00       2.000000       2.000000       3.000000  2.000000e+01
REGION_RATING_CLIENT         307511.0       2.052463       0.509034  1.000000e+00       2.000000       2.000000       2.000000  3.000000e+00
REGION_RATING_CLIENT_W_CITY  307511.0       2.031521       0.502737  1.000000e+00       2.000000       2.000000       2.000000  3.000000e+00
HOUR_APPR_PROCESS_START      307511.0      12.063419       3.265832  0.000000e+00      10.000000      12.000000      14.000000  2.300000e+01
REG_REGION_NOT_LIVE_REGION   307511.0       0.015144       0.122126  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
REG_REGION_NOT_WORK_REGION   307511.0       0.050769       0.219526  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
LIVE_REGION_NOT_WORK_REGION  307511.0       0.040659       0.197499  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
REG_CITY_NOT_LIVE_CITY       307511.0       0.078173       0.268444  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
REG_CITY_NOT_WORK_CITY       307511.0       0.230454       0.421124  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
LIVE_CITY_NOT_WORK_CITY      307511.0       0.179555       0.383817  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
EXT_SOURCE_2                 307511.0       0.514393       0.190855  8.173617e-08       0.392974       0.565467       0.663422  8.549997e-01
OBS_30_CNT_SOCIAL_CIRCLE     306490.0       1.422245       2.400989  0.000000e+00       0.000000       0.000000       2.000000  3.480000e+02
DEF_30_CNT_SOCIAL_CIRCLE     306490.0       0.143421       0.446698  0.000000e+00       0.000000       0.000000       0.000000  3.400000e+01
OBS_60_CNT_SOCIAL_CIRCLE     306490.0       1.405292       2.379803  0.000000e+00       0.000000       0.000000       2.000000  3.440000e+02
DEF_60_CNT_SOCIAL_CIRCLE     306490.0       0.100049       0.362291  0.000000e+00       0.000000       0.000000       0.000000  2.400000e+01
DAYS_LAST_PHONE_CHANGE       307511.0    -962.858788     826.807143 -4.292000e+03   -1570.000000    -757.000000    -274.000000  0.000000e+00
FLAG_DOCUMENT_2              307511.0       0.000042       0.006502  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_3              307511.0       0.710023       0.453752  0.000000e+00       0.000000       1.000000       1.000000  1.000000e+00
FLAG_DOCUMENT_4              307511.0       0.000081       0.009016  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_5              307511.0       0.015115       0.122010  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_6              307511.0       0.088055       0.283376  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_7              307511.0       0.000192       0.013850  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_8              307511.0       0.081376       0.273412  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_9              307511.0       0.003896       0.062295  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_10             307511.0       0.000023       0.004771  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_11             307511.0       0.003912       0.062424  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_12             307511.0       0.000007       0.002550  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_13             307511.0       0.003525       0.059268  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_14             307511.0       0.002936       0.054110  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_15             307511.0       0.001210       0.034760  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_16             307511.0       0.009928       0.099144  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_17             307511.0       0.000267       0.016327  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_18             307511.0       0.008130       0.089798  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_19             307511.0       0.000595       0.024387  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_20             307511.0       0.000507       0.022518  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_21             307511.0       0.000335       0.018299  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
AMT_REQ_CREDIT_BUREAU_HOUR   265992.0       0.006402       0.083849  0.000000e+00       0.000000       0.000000       0.000000  4.000000e+00
AMT_REQ_CREDIT_BUREAU_DAY    265992.0       0.007000       0.110757  0.000000e+00       0.000000       0.000000       0.000000  9.000000e+00
AMT_REQ_CREDIT_BUREAU_WEEK   265992.0       0.034362       0.204685  0.000000e+00       0.000000       0.000000       0.000000  8.000000e+00
AMT_REQ_CREDIT_BUREAU_MON    265992.0       0.267395       0.916002  0.000000e+00       0.000000       0.000000       0.000000  2.700000e+01
AMT_REQ_CREDIT_BUREAU_QRT    265992.0       0.265474       0.794056  0.000000e+00       0.000000       0.000000       0.000000  2.610000e+02
AMT_REQ_CREDIT_BUREAU_YEAR   265992.0       1.899974       1.869295  0.000000e+00       0.000000       1.000000       3.000000  2.500000e+01

In [234]:
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
outlier_df = application_data.select_dtypes(include=numerics)

In [235]:
outlier_df.describe().T

                                count           mean            std           min            25%            50%            75%           max
SK_ID_CURR                   307511.0  278180.518577  102790.175348  1.000020e+05  189145.500000  278202.000000  367142.500000  4.562550e+05
TARGET                       307511.0       0.080729       0.272419  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
CNT_CHILDREN                 307511.0       0.417052       0.722121  0.000000e+00       0.000000       0.000000       1.000000  1.900000e+01
AMT_INCOME_TOTAL             307511.0  168797.919297  237123.146279  2.565000e+04  112500.000000  147150.000000  202500.000000  1.170000e+08
AMT_CREDIT                   307511.0  599025.999706  402490.776996  4.500000e+04  270000.000000  513531.000000  808650.000000  4.050000e+06
AMT_ANNUITY                  307511.0   27108.573909   14493.454517  1.615500e+03   16524.000000   24903.000000   34596.000000  2.580255e+05
AMT_GOODS_PRICE              307511.0  538396.207429  369279.426396  4.050000e+04  238500.000000  450000.000000  679500.000000  4.050000e+06
REGION_POPULATION_RELATIVE   307511.0       0.020868       0.013831  2.900000e-04       0.010006       0.018850       0.028663  7.250800e-02
DAYS_BIRTH                   307511.0  -16036.995067    4363.988632 -2.522900e+04  -19682.000000  -15750.000000  -12413.000000 -7.489000e+03
DAYS_EMPLOYED                307511.0   63815.045904  141275.766519 -1.791200e+04   -2760.000000   -1213.000000    -289.000000  3.652430e+05
DAYS_REGISTRATION            307511.0   -4986.120328    3522.886321 -2.467200e+04   -7479.500000   -4504.000000   -2010.000000  0.000000e+00
DAYS_ID_PUBLISH              307511.0   -2994.202373    1509.450419 -7.197000e+03   -4299.000000   -3254.000000   -1720.000000  0.000000e+00
FLAG_MOBIL                   307511.0       0.999997       0.001803  0.000000e+00       1.000000       1.000000       1.000000  1.000000e+00
FLAG_EMP_PHONE               307511.0       0.819889       0.384280  0.000000e+00       1.000000       1.000000       1.000000  1.000000e+00
FLAG_WORK_PHONE              307511.0       0.199368       0.399526  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_CONT_MOBILE             307511.0       0.998133       0.043164  0.000000e+00       1.000000       1.000000       1.000000  1.000000e+00
FLAG_PHONE                   307511.0       0.281066       0.449521  0.000000e+00       0.000000       0.000000       1.000000  1.000000e+00
FLAG_EMAIL                   307511.0       0.056720       0.231307  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
CNT_FAM_MEMBERS              307511.0       2.152665       0.910679  1.000000e+00       2.000000       2.000000       3.000000  2.000000e+01
REGION_RATING_CLIENT         307511.0       2.052463       0.509034  1.000000e+00       2.000000       2.000000       2.000000  3.000000e+00
REGION_RATING_CLIENT_W_CITY  307511.0       2.031521       0.502737  1.000000e+00       2.000000       2.000000       2.000000  3.000000e+00
HOUR_APPR_PROCESS_START      307511.0      12.063419       3.265832  0.000000e+00      10.000000      12.000000      14.000000  2.300000e+01
REG_REGION_NOT_LIVE_REGION   307511.0       0.015144       0.122126  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
REG_REGION_NOT_WORK_REGION   307511.0       0.050769       0.219526  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
LIVE_REGION_NOT_WORK_REGION  307511.0       0.040659       0.197499  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
REG_CITY_NOT_LIVE_CITY       307511.0       0.078173       0.268444  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
REG_CITY_NOT_WORK_CITY       307511.0       0.230454       0.421124  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
LIVE_CITY_NOT_WORK_CITY      307511.0       0.179555       0.383817  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
EXT_SOURCE_2                 307511.0       0.514393       0.190855  8.173617e-08       0.392974       0.565467       0.663422  8.549997e-01
OBS_30_CNT_SOCIAL_CIRCLE     306490.0       1.422245       2.400989  0.000000e+00       0.000000       0.000000       2.000000  3.480000e+02
DEF_30_CNT_SOCIAL_CIRCLE     306490.0       0.143421       0.446698  0.000000e+00       0.000000       0.000000       0.000000  3.400000e+01
OBS_60_CNT_SOCIAL_CIRCLE     306490.0       1.405292       2.379803  0.000000e+00       0.000000       0.000000       2.000000  3.440000e+02
DEF_60_CNT_SOCIAL_CIRCLE     306490.0       0.100049       0.362291  0.000000e+00       0.000000       0.000000       0.000000  2.400000e+01
DAYS_LAST_PHONE_CHANGE       307511.0    -962.858788     826.807143 -4.292000e+03   -1570.000000    -757.000000    -274.000000  0.000000e+00
FLAG_DOCUMENT_2              307511.0       0.000042       0.006502  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_3              307511.0       0.710023       0.453752  0.000000e+00       0.000000       1.000000       1.000000  1.000000e+00
FLAG_DOCUMENT_4              307511.0       0.000081       0.009016  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_5              307511.0       0.015115       0.122010  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_6              307511.0       0.088055       0.283376  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_7              307511.0       0.000192       0.013850  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_8              307511.0       0.081376       0.273412  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_9              307511.0       0.003896       0.062295  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_10             307511.0       0.000023       0.004771  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_11             307511.0       0.003912       0.062424  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_12             307511.0       0.000007       0.002550  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_13             307511.0       0.003525       0.059268  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_14             307511.0       0.002936       0.054110  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_15             307511.0       0.001210       0.034760  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_16             307511.0       0.009928       0.099144  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_17             307511.0       0.000267       0.016327  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_18             307511.0       0.008130       0.089798  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_19             307511.0       0.000595       0.024387  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_20             307511.0       0.000507       0.022518  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
FLAG_DOCUMENT_21             307511.0       0.000335       0.018299  0.000000e+00       0.000000       0.000000       0.000000  1.000000e+00
AMT_REQ_CREDIT_BUREAU_HOUR   265992.0       0.006402       0.083849  0.000000e+00       0.000000       0.000000       0.000000  4.000000e+00
AMT_REQ_CREDIT_BUREAU_DAY    265992.0       0.007000       0.110757  0.000000e+00       0.000000       0.000000       0.000000  9.000000e+00
AMT_REQ_CREDIT_BUREAU_WEEK   265992.0       0.034362       0.204685  0.000000e+00       0.000000       0.000000       0.000000  8.000000e+00
AMT_REQ_CREDIT_BUREAU_MON    265992.0       0.267395       0.916002  0.000000e+00       0.000000       0.000000       0.000000  2.700000e+01
AMT_REQ_CREDIT_BUREAU_QRT    265992.0       0.265474       0.794056  0.000000e+00       0.000000       0.000000       0.000000  2.610000e+02
AMT_REQ_CREDIT_BUREAU_YEAR   265992.0       1.899974       1.869295  0.000000e+00       0.000000       1.000000       3.000000  2.500000e+01

In [ ]:
for cols,values in outlier_df.iteritems():
    f, ax = plt.subplots(1,1,figsize=(8,8))
    f.suptitle(cols, fontsize=16)
    outlier_plot = sns.distplot(outlier_df[cols])